// Central UI string table for the four family languages.
// Person content (names/roles/stories) is translated per-record; this covers the
// app chrome so the whole interface switches with the language toggle.

const STRINGS = {
  en: {
    'lens.lineage': 'Lineage',
    'lens.overview': 'Overview',
    'lens.timeline': 'Timeline',
    'lens.map': 'Places',
    'action.home': 'Home',
    'action.search': 'Search',
    'action.add': 'Add person',
    'action.back': 'Back',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'action.cancel': 'Cancel',
    'action.save': 'Save',
    'action.saving': 'Saving…',
    'action.center': 'Center on tree',
    'action.markAsMe': 'Mark as me',
    'action.markAsMeActive': 'This is me',
    'action.addRelative': '+ Add a relative',
    'action.signOut': 'Sign out',
    'action.play': 'Play story',
    'action.stop': 'Stop',
    'action.relate': 'How are we related?',
    'label.story': 'Story',
    'label.parents': 'Parents',
    'label.partner': 'Partner',
    'label.siblings': 'Siblings',
    'label.children': 'Children',
    'label.memories': 'Memories',
    'label.admin': 'Admin',
    'label.viewingLineage': 'Viewing lineage',
    'label.born': 'Born',
    'label.places': 'Places',
    'label.birthPlace': 'Birth place',
    'title.familyAccess': 'Family access',
    'title.editPerson': 'Edit person',
    'title.addPerson': 'Add a person',
    'memory.add': 'Add a memory',
    'memory.placeholder': 'Share a memory of this person…',
    'memory.yourName': 'Your name',
    'memory.empty': 'No memories yet. Be the first to share one.',
    'memory.post': 'Share',
    'today.birthday': 'Today is {name}’s birthday',
    'today.remembering': 'Remembering {name} today',
    'relate.prompt': 'Tap another person to see how you are related.',
    'relate.pickFirst': 'Tap a person to begin.',
    'relate.same': 'This is the same person.',
    'relate.none': 'No direct family path found.',
    'relate.result': '{target} is your {relation} · from {anchor}',
    'story.title': 'The family story',
    'story.gen.elders': 'The elders',
    'story.gen.focal': 'This generation',
    'story.gen.children': 'The next generation',
    'story.gen.generation': 'Generation {n}',
    'story.listen': 'Listen',
    'story.mute': 'Mute voice',
    'misc.peopleGenerations': '{people} people · {generations} generations',
    'misc.noStory': 'No story yet.',
    'misc.noOne': 'No one to show yet.',
    'public.on': 'Anyone with the link can view',
    'public.off': 'Private to members',
    'public.linkHint': 'Send this link to family. No sign-in or email needed.',
    'public.copyLink': 'Copy link',
    'public.copied': 'Copied!',
    'public.enableFirst': 'Turn on public viewing above, then share the link.',
    'public.viewOnly': 'Family can browse and search — view only. Only the admin can make changes.',
    'action.adminSignIn': 'Admin sign in',
    'admin.signInHint': 'Sign in with the email that owns this tree. Your session stays saved on this device.',
    'admin.checkEmail': 'Check your email',
    'admin.sentTo': 'We sent a sign-in link to',
    'admin.sending': 'Sending…',
    'admin.signInError': 'Could not send the link. Please try again.',
    'kin.self': 'you',
    'kin.parent': 'parent',
    'kin.father': 'father',
    'kin.mother': 'mother',
    'kin.child': 'child',
    'kin.son': 'son',
    'kin.daughter': 'daughter',
    'kin.sibling': 'sibling',
    'kin.brother': 'brother',
    'kin.sister': 'sister',
    'kin.partner': 'partner',
    'kin.grandparent': 'grandparent',
    'kin.grandchild': 'grandchild',
    'kin.greatgrandparent': 'great-grandparent',
    'kin.greatgrandchild': 'great-grandchild',
    'kin.auntuncle': 'aunt/uncle',
    'kin.niecenephew': 'niece/nephew',
    'kin.cousin': 'cousin',
    'kin.inlaw': 'in-law',
    'kin.related': 'related',
  },
  fr: {
    'lens.lineage': 'Lignée',
    'lens.overview': "Vue d’ensemble",
    'lens.timeline': 'Chronologie',
    'lens.map': 'Lieux',
    'action.home': 'Accueil',
    'action.search': 'Rechercher',
    'action.add': 'Ajouter',
    'action.back': 'Retour',
    'action.edit': 'Modifier',
    'action.delete': 'Supprimer',
    'action.cancel': 'Annuler',
    'action.save': 'Enregistrer',
    'action.saving': 'Enregistrement…',
    'action.center': "Centrer sur l’arbre",
    'action.markAsMe': 'C’est moi',
    'action.markAsMeActive': 'C’est moi',
    'action.addRelative': '+ Ajouter un proche',
    'action.signOut': 'Se déconnecter',
    'action.play': "Lire l’histoire",
    'action.stop': 'Arrêter',
    'action.relate': 'Quel est notre lien ?',
    'label.story': 'Histoire',
    'label.parents': 'Parents',
    'label.partner': 'Partenaire',
    'label.siblings': 'Frères et sœurs',
    'label.children': 'Enfants',
    'label.memories': 'Souvenirs',
    'label.admin': 'Admin',
    'label.viewingLineage': 'Lignée affichée',
    'label.born': 'Né(e)',
    'label.places': 'Lieux',
    'label.birthPlace': 'Lieu de naissance',
    'title.familyAccess': 'Accès famille',
    'title.editPerson': 'Modifier la personne',
    'title.addPerson': 'Ajouter une personne',
    'memory.add': 'Ajouter un souvenir',
    'memory.placeholder': 'Partagez un souvenir de cette personne…',
    'memory.yourName': 'Votre nom',
    'memory.empty': 'Aucun souvenir. Soyez le premier à en partager un.',
    'memory.post': 'Partager',
    'today.birthday': "Aujourd’hui, c’est l’anniversaire de {name}",
    'today.remembering': 'Nous nous souvenons de {name}',
    'relate.prompt': 'Touchez une autre personne pour voir votre lien.',
    'relate.pickFirst': 'Touchez une personne pour commencer.',
    'relate.same': 'C’est la même personne.',
    'relate.none': 'Aucun lien familial direct trouvé.',
    'relate.result': '{target} est votre {relation} · depuis {anchor}',
    'story.title': 'L’histoire de la famille',
    'story.gen.elders': 'Les aînés',
    'story.gen.focal': 'Cette génération',
    'story.gen.children': 'La génération suivante',
    'story.gen.generation': 'Génération {n}',
    'story.listen': 'Écouter',
    'story.mute': 'Couper la voix',
    'misc.peopleGenerations': '{people} personnes · {generations} générations',
    'misc.noStory': 'Pas encore d’histoire.',
    'misc.noOne': 'Personne à afficher.',
    'public.on': 'Toute personne avec le lien peut voir',
    'public.off': 'Privé aux membres',
    'public.linkHint': 'Envoyez ce lien à la famille. Pas de connexion ni d’e-mail requis.',
    'public.copyLink': 'Copier le lien',
    'public.copied': 'Copié !',
    'public.enableFirst': 'Activez l’accès public ci-dessus, puis partagez le lien.',
    'public.viewOnly': 'La famille peut parcourir — lecture seule. Seul l’admin peut modifier.',
    'action.adminSignIn': 'Connexion admin',
    'admin.signInHint': 'Connectez-vous avec l’e-mail qui possède cet arbre. La session reste enregistrée sur cet appareil.',
    'admin.checkEmail': 'Vérifiez votre e-mail',
    'admin.sentTo': 'Lien envoyé à',
    'admin.sending': 'Envoi…',
    'admin.signInError': 'Impossible d’envoyer le lien. Réessayez.',
    'kin.self': 'vous',
    'kin.parent': 'parent',
    'kin.father': 'père',
    'kin.mother': 'mère',
    'kin.child': 'enfant',
    'kin.son': 'fils',
    'kin.daughter': 'fille',
    'kin.sibling': 'frère/sœur',
    'kin.brother': 'frère',
    'kin.sister': 'sœur',
    'kin.partner': 'partenaire',
    'kin.grandparent': 'grand-parent',
    'kin.grandchild': 'petit-enfant',
    'kin.greatgrandparent': 'arrière-grand-parent',
    'kin.greatgrandchild': 'arrière-petit-enfant',
    'kin.auntuncle': 'tante/oncle',
    'kin.niecenephew': 'nièce/neveu',
    'kin.cousin': 'cousin(e)',
    'kin.inlaw': 'par alliance',
    'kin.related': 'lié(e)',
  },
  ln: {
    'lens.lineage': 'Libota',
    'lens.overview': 'Komona nyonso',
    'lens.timeline': 'Ntango',
    'lens.map': 'Bisika',
    'action.home': 'Ndako',
    'action.search': 'Luka',
    'action.add': 'Bakisa',
    'action.back': 'Zonga',
    'action.edit': 'Bongola',
    'action.delete': 'Longola',
    'action.cancel': 'Tika',
    'action.save': 'Bomba',
    'action.saving': 'Kobomba…',
    'action.center': 'Tia na kati',
    'action.markAsMe': 'Nazali ngai',
    'action.markAsMeActive': 'Nazali ngai',
    'action.addRelative': '+ Bakisa moto ya libota',
    'action.signOut': 'Bima',
    'action.play': 'Tala lisolo',
    'action.stop': 'Tɛlɛma',
    'action.relate': 'Tozali boníboni?',
    'label.story': 'Lisolo',
    'label.parents': 'Baboti',
    'label.partner': 'Molongani',
    'label.siblings': 'Bandeko',
    'label.children': 'Bana',
    'label.memories': 'Makanisi',
    'label.admin': 'Admin',
    'label.viewingLineage': 'Kotala libota',
    'label.born': 'Abotama',
    'label.places': 'Bisika',
    'label.birthPlace': 'Esika ya mbotama',
    'title.familyAccess': 'Bokɔti ya libota',
    'title.editPerson': 'Bongola moto',
    'title.addPerson': 'Bakisa moto',
    'memory.add': 'Bakisa likanisi',
    'memory.placeholder': 'Kabola likanisi ya moto oyo…',
    'memory.yourName': 'Kombo na yo',
    'memory.empty': 'Makanisi ezali naino te. Zala ya liboso.',
    'memory.post': 'Kabola',
    'today.birthday': 'Lelo ezali mokolo ya mbotama ya {name}',
    'today.remembering': 'Tozali kokanisa {name} lelo',
    'relate.prompt': 'Finá moto mosusu mpo na komona boyokani.',
    'relate.pickFirst': 'Finá moto mpo na kobanda.',
    'relate.same': 'Ezali moto se moko.',
    'relate.none': 'Boyokani ya libota emonani te.',
    'relate.result': '{target} ezali {relation} na yo · uta na {anchor}',
    'story.title': 'Lisolo ya libota',
    'story.gen.elders': 'Bakolo',
    'story.gen.focal': 'Lizini oyo',
    'story.gen.children': 'Lizini elandi',
    'story.gen.generation': 'Lizini {n}',
    'story.listen': 'Yoka',
    'story.mute': 'Longola mongongo',
    'misc.peopleGenerations': 'bato {people} · mabota {generations}',
    'misc.noStory': 'Lisolo ezali naino te.',
    'misc.noOne': 'Moto ya kolakisa azali te.',
    'public.on': 'Moto nyonso na lien akoki kotala',
    'public.off': 'Ya bandimi kaka',
    'public.linkHint': 'Tinda lien oyo na libota. Motema te na kokota to email.',
    'public.copyLink': 'Kopí lien',
    'public.copied': 'Ekopami!',
    'public.enableFirst': 'Fungola libotala ya bato nyonso, sima tinda lien.',
    'public.viewOnly': 'Libota ekoki kotala kaka — kobongola ezali mpo na admin kaka.',
    'action.adminSignIn': 'Kokota admin',
    'admin.signInHint': 'Kota na email ya mobu ya libota. Session ekosala kaka na aparɛyi oyo.',
    'admin.checkEmail': 'Talá email na yo',
    'admin.sentTo': 'Tolí linki na',
    'admin.sending': 'Ezali kotinda…',
    'admin.signInError': 'Linki ekokaki kotindama te.',
    'kin.self': 'yo',
    'kin.parent': 'moboti',
    'kin.father': 'tata',
    'kin.mother': 'mama',
    'kin.child': 'mwana',
    'kin.son': 'mwana mobali',
    'kin.daughter': 'mwana mwasi',
    'kin.sibling': 'ndeko',
    'kin.brother': 'ndeko mobali',
    'kin.sister': 'ndeko mwasi',
    'kin.partner': 'molongani',
    'kin.grandparent': 'nkɔkɔ',
    'kin.grandchild': 'mwana ya mwana',
    'kin.greatgrandparent': 'nkɔkɔ ya nkɔkɔ',
    'kin.greatgrandchild': 'mwana ya mwana ya mwana',
    'kin.auntuncle': 'noko/tata leki',
    'kin.niecenephew': 'mwana ya ndeko',
    'kin.cousin': 'ndeko',
    'kin.inlaw': 'ya libala',
    'kin.related': 'boyokani',
  },
  sw: {
    'lens.lineage': 'Ukoo',
    'lens.overview': 'Muonekano',
    'lens.timeline': 'Ratiba',
    'lens.map': 'Maeneo',
    'action.home': 'Nyumbani',
    'action.search': 'Tafuta',
    'action.add': 'Ongeza',
    'action.back': 'Rudi',
    'action.edit': 'Hariri',
    'action.delete': 'Futa',
    'action.cancel': 'Ghairi',
    'action.save': 'Hifadhi',
    'action.saving': 'Inahifadhi…',
    'action.center': 'Weka katikati',
    'action.markAsMe': 'Huyu ni mimi',
    'action.markAsMeActive': 'Huyu ni mimi',
    'action.addRelative': '+ Ongeza ndugu',
    'action.signOut': 'Toka',
    'action.play': 'Cheza hadithi',
    'action.stop': 'Simamisha',
    'action.relate': 'Tunahusianaje?',
    'label.story': 'Hadithi',
    'label.parents': 'Wazazi',
    'label.partner': 'Mwenzi',
    'label.siblings': 'Ndugu',
    'label.children': 'Watoto',
    'label.memories': 'Kumbukumbu',
    'label.admin': 'Msimamizi',
    'label.viewingLineage': 'Unatazama ukoo',
    'label.born': 'Alizaliwa',
    'label.places': 'Maeneo',
    'label.birthPlace': 'Mahali pa kuzaliwa',
    'title.familyAccess': 'Ufikiaji wa familia',
    'title.editPerson': 'Hariri mtu',
    'title.addPerson': 'Ongeza mtu',
    'memory.add': 'Ongeza kumbukumbu',
    'memory.placeholder': 'Shiriki kumbukumbu ya mtu huyu…',
    'memory.yourName': 'Jina lako',
    'memory.empty': 'Hakuna kumbukumbu bado. Kuwa wa kwanza kushiriki.',
    'memory.post': 'Shiriki',
    'today.birthday': 'Leo ni siku ya kuzaliwa ya {name}',
    'today.remembering': 'Tunamkumbuka {name} leo',
    'relate.prompt': 'Gusa mtu mwingine kuona uhusiano wenu.',
    'relate.pickFirst': 'Gusa mtu kuanza.',
    'relate.same': 'Huyu ni mtu yule yule.',
    'relate.none': 'Hakuna uhusiano wa moja kwa moja.',
    'relate.result': '{target} ni {relation} yako · kutoka {anchor}',
    'story.title': 'Hadithi ya familia',
    'story.gen.elders': 'Wazee',
    'story.gen.focal': 'Kizazi hiki',
    'story.gen.children': 'Kizazi kinachofuata',
    'story.gen.generation': 'Kizazi {n}',
    'story.listen': 'Sikiliza',
    'story.mute': 'Nyamazisha sauti',
    'misc.peopleGenerations': 'watu {people} · vizazi {generations}',
    'misc.noStory': 'Hakuna hadithi bado.',
    'misc.noOne': 'Hakuna wa kuonyesha bado.',
    'public.on': 'Yeyote mwenye kiungo anaweza kuona',
    'public.off': 'Ya wanachama pekee',
    'public.linkHint': 'Tuma kiungo hiki kwa familia. Hakuna kuingia au barua pepe.',
    'public.copyLink': 'Nakili kiungo',
    'public.copied': 'Imenakiliwa!',
    'public.enableFirst': 'Washa mwonekano wa umma hapo juu, kisha shiriki kiungo.',
    'public.viewOnly': 'Familia inaweza kutazama tu — hakuna kuhariri isipokuwa admin.',
    'action.adminSignIn': 'Ingia kama admin',
    'admin.signInHint': 'Ingia kwa barua pepe ya mmiliki wa mti. Kikao kinabaki kwenye kifaa hiki.',
    'admin.checkEmail': 'Angalia barua pepe yako',
    'admin.sentTo': 'Tumetuma kiungo kwa',
    'admin.sending': 'Inatuma…',
    'admin.signInError': 'Imeshindwa kutuma kiungo. Jaribu tena.',
    'kin.self': 'wewe',
    'kin.parent': 'mzazi',
    'kin.father': 'baba',
    'kin.mother': 'mama',
    'kin.child': 'mtoto',
    'kin.son': 'mwana wa kiume',
    'kin.daughter': 'binti',
    'kin.sibling': 'ndugu',
    'kin.brother': 'kaka',
    'kin.sister': 'dada',
    'kin.partner': 'mwenzi',
    'kin.grandparent': 'babu/bibi',
    'kin.grandchild': 'mjukuu',
    'kin.greatgrandparent': 'babu mkuu',
    'kin.greatgrandchild': 'kitukuu',
    'kin.auntuncle': 'shangazi/mjomba',
    'kin.niecenephew': 'mpwa',
    'kin.cousin': 'binamu',
    'kin.inlaw': 'wa ndoa',
    'kin.related': 'uhusiano',
  },
}

export function getUIString(key, language, vars) {
  const table = STRINGS[language] || STRINGS.en
  let str = table[key] ?? STRINGS.en[key] ?? key
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      str = str.replace(`{${k}}`, v)
    }
  }
  return str
}

export default STRINGS
